export enum ACTIONS {
  CARDS_REQUEST_DATA = 'CARDS_REQUEST_DATA',
  CARDS_RECEIVE_DATA = 'CARDS_RECEIVE_DATA',
  CARDS_REJECT_DATA = 'CARDS_REJECT_DATA',
  CARDS_REQUEST_END = 'CARDS_REQUEST_END',
  CARDS_DELETE_CARD = 'CARDS_DELETE_CARD',
  CARDS_LIKE_CARD = 'CARDS_LIKE_CARD',
  CARDS_UNLIKE_CARD = 'CARDS_UNLIKE_CARD',
}
